# Generated by Django 2.0.5 on 2018-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wo',
            fields=[
                ('wo_number', models.AutoField(max_length=8, primary_key=True, serialize=False)),
                ('planner_id', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('functional_location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('status_report', models.TextField()),
            ],
        ),
    ]
