# Generated by Django 2.0.5 on 2018-05-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20180518_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='fucntional_location',
            new_name='functional_location',
        ),
    ]
