# Generated by Django 2.0.5 on 2018-05-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_auto_20180518_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='functional_location',
            field=models.CharField(max_length=200),
        ),
    ]
